// SPDX-License-Identifier: Apache-2.0
package ai.intellistream.datahub.resource;
import tools.jackson.databind.annotation.JsonSerialize;
import ai.intellistream.datahub.json.ToStringSerializer;

import ai.intellistream.datahub.models.validation.ForbiddenValues;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

import java.time.ZonedDateTime;
import java.util.HashMap;
import java.util.Map;

@EqualsAndHashCode(of = {"id", "externalId"})
@Schema(name="Node", description="Node description")
@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_NULL)
public class NodeForm {

    /**
     * Unique id reference generated by DataHub.
     */
    @JsonSerialize(using = ToStringSerializer.class)
    private Long id;

    /**
     * Unique id reference generated by Neo4j.
     */
    @JsonIgnore
    private Long elementId;

    /**
     * The external ID. Unique name for the asset, a human read-able ID.
     */
    @NotNull
    @NotBlank
    @Size(min = 3, max = 256)
    @ForbiddenValues(message = "Forbidden value for external id.")
    private String externalId;

    /**
     * Asset root id reference, the starting point for navigation asset relations
     */
    private Boolean isRoot = false;

    /**
     * The name of the asset.
     */
    @NotBlank
    @NotNull
    @Size(min = 3, max = 512)
    private String name;

    /**
     * Entity specific metadata. A key-value store.
     */
    private Map<String, String> metadata = new HashMap<>();

    /**
     * The description of the asset.
     */
    private String description;


    /**
     * The id of the data set this asset belongs to.
     */
    @JsonSerialize(using = ToStringSerializer.class)
    private Long dataSetId;

    private ZonedDateTime createdTime;

    private ZonedDateTime lastUpdatedTime;

    public NodeForm() {
    }

    public void setExternalId(String externalId){
        this.externalId = externalId;
    }

    public void setIsRoot(Boolean v){
        if(v != null){
            this.isRoot = v;
        }
    }

}
