// SPDX-License-Identifier: AGPL-3.0-or-later
package ai.intellistream.datahub.models.forms;

import ai.intellistream.datahub.models.RelForm;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class RelFormWithId extends RelForm {

    /**
     * Unique id reference generated by DataHub.
     */
    @NotNull
    private Long id;

}
