-- V13__refactor_governance.sql

-- 1 Insert new POLICY node type
INSERT INTO node_type (name, description, date_created, last_updated)
SELECT 'POLICY', 'Represents a shared policy configuration node', current_timestamp, current_timestamp
    WHERE NOT EXISTS (SELECT 1 FROM node_type WHERE name = 'POLICY');

-- 2 Governance template table
CREATE TABLE governance_template
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(128) NOT NULL,
    description         TEXT,
    external_id         VARCHAR(255),
    external_id_hash    BIGINT,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3 Template metadata (key/value)
CREATE TABLE governance_template_metadata
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id     BIGINT NOT NULL,
    key             VARCHAR(256) NOT NULL,
    value           VARCHAR(512),
    FOREIGN KEY (template_id) REFERENCES governance_template(id) ON DELETE CASCADE
);

CREATE INDEX governance_template_metadata_template_id_key_key
    ON governance_template_metadata (template_id, key);

COMMENT ON TABLE governance_template
    IS 'Defines reusable sets of metadata defaults for policy nodes.';

COMMENT ON TABLE governance_template_metadata
    IS 'Stores key/value pairs for each governance template.';

-- 4 Ensure uniqueness for lookup via hash
CREATE UNIQUE INDEX IF NOT EXISTS uk_governance_template_external_id_hash
    ON governance_template (external_id_hash);

-- 5 Backfill only affects rows created BEFORE API inserts external_id
UPDATE governance_template
SET external_id = LOWER(REPLACE(name, ' ', '_'))
WHERE external_id IS NULL;

UPDATE governance_template
SET external_id_hash = MOD(ABS(HASHTEXT(external_id)), 9223372036854775807)
WHERE external_id_hash IS NULL;
