-- Label
CREATE TABLE label
(
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash            bigint NOT NULL,
    name            varchar(512) NOT NULL,
    description     text NULL,
    i18n_code       text NULL,
    color           varchar(7) NOT NULL, --HTML color
    date_created    timestamp WITH TIME ZONE,
    last_updated    timestamp WITH TIME ZONE,
    CONSTRAINT label_hash_key UNIQUE (hash)
);

-- DataSet
CREATE TABLE data_set
(
    id                int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id         int NULL,
    external_id       varchar(256) NOT NULL,
    hash              bigint NOT NULL,
    deactivated       boolean not null DEFAULT FALSE,
    write_protected   boolean not null DEFAULT FALSE,
    name              varchar(512) NOT NULL,
    description       text NULL,
    date_created      timestamp WITH TIME ZONE,
    last_updated      timestamp WITH TIME ZONE,
    CONSTRAINT data_set_hash_key UNIQUE (hash),
    CONSTRAINT data_set_parent_id_fk
        FOREIGN KEY(parent_id)
            REFERENCES data_set(id)
);
-- Btree is better for exact matches and pattern matching at the beginning of strings
CREATE INDEX data_set_external_id_idx ON data_set USING btree (external_id);
CREATE INDEX data_set_name_idx ON data_set USING GIN (to_tsvector('simple', name));
-- DataSet Metadata
CREATE TABLE dataset_metadata
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id          int NOT NULL,
    key                 varchar(1024) NOT NULL,
    value               text NULL,
    CONSTRAINT dataset_metadata_dataset_id_fk
        FOREIGN KEY(dataset_id)
            REFERENCES data_set(id)
);
CREATE INDEX dataset_metadata_dataset_id_key_value_idx ON dataset_metadata USING btree (dataset_id, key, value);

-- Create Node Tables
CREATE TABLE node_type(
    id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                varchar(512) NOT NULL,
    description         text NULL,
    date_created        timestamp WITH TIME ZONE,
    last_updated        timestamp WITH TIME ZONE
);
INSERT INTO node_type (name, description, date_created, last_updated) VALUES
('ASSET', 'Asset node type', current_timestamp, current_timestamp),
('TIMESERIES', 'Timeseries node type', current_timestamp, current_timestamp),
('FUNCTION', 'Function node type', current_timestamp, current_timestamp),
('RESOURCE', 'Resource node type', current_timestamp, current_timestamp);

CREATE TABLE asset
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source              text NULL
);
-- Create function entity
CREATE TABLE function_entity
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    i18n_code       text NULL
);

-- Timeseries
CREATE TABLE timeseries (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_string               boolean not null DEFAULT FALSE,
    is_step                 boolean not null DEFAULT FALSE,
    unit                    varchar(64) not null,
    value_type_id           int NOT NULL,
    table_engine            int NOT NULL
);

CREATE TABLE node
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                varchar(512) NOT NULL,
    description         text NULL,
    external_id         varchar(256) NOT NULL,
    external_id_hash    bigint NOT NULL,
    asset_id            bigint NULL,
    timeseries_id       bigint NULL,
    function_id         bigint NULL,
    labels              text NULL,
    data_set_id         int NULL,
    date_created        timestamp WITH TIME ZONE,
    last_updated        timestamp WITH TIME ZONE,
    is_root             bool NOT NULL DEFAULT false,
    node_type_id        int,
    CONSTRAINT node_external_id_hash_key UNIQUE (external_id_hash),
    CONSTRAINT node_node_type_id_fk
        FOREIGN KEY(node_type_id)
            REFERENCES node_type(id),
    CONSTRAINT node_asset_id_fk
        FOREIGN KEY(asset_id)
            REFERENCES asset(id),
    CONSTRAINT node_timeseries_id_fk
        FOREIGN KEY(timeseries_id)
            REFERENCES timeseries(id),
    CONSTRAINT node_function_id_fk
        FOREIGN KEY(function_id)
            REFERENCES function_entity(id)
);
CREATE INDEX node_name_idx ON node USING GIN (to_tsvector('simple', name));
CREATE INDEX node_id_node_type_id_idx ON node USING BTREE (id, node_type_id);
-- Look into creating pg_trgm extension with trigrams for even better performance
-- CREATE INDEX asset_node_name_uc_idx ON asset_node USING btree (name);

ALTER TABLE node
    ADD CONSTRAINT node_data_set_id_fk
        FOREIGN KEY (data_set_id)
            REFERENCES data_set(id);

-- Node Metadata
CREATE TABLE node_metadata
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id             bigint NOT NULL,
    key                 varchar(1024) NOT NULL,
    value               text NULL,
    CONSTRAINT node_data_node_id_fk
        FOREIGN KEY(node_id)
            REFERENCES node(id)
);
CREATE INDEX node_metadata_node_id_idx ON node_metadata USING btree (node_id, key, value);

-- Node Labels Many to Many
CREATE TABLE node_labels(
    node_id bigint NOT NULL REFERENCES node(id),
    label_id bigint NOT NULL REFERENCES label(id)
);
CREATE INDEX node_labels_node_id_idx ON node_labels USING btree (node_id, label_id);

-- Relationship Type
CREATE TABLE relationship_type
(
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash            bigint NOT NULL,
    name            varchar(512) NOT NULL,
    description     text NULL,
    i18n_code       text NULL,
    date_created    timestamp WITH TIME ZONE,
    last_updated    timestamp WITH TIME ZONE,
    CONSTRAINT relationship_hash_key UNIQUE (hash)
);

CREATE INDEX relationship_hash_idx ON relationship_type USING BTREE (name);
CREATE INDEX relationship_name_idx ON relationship_type USING GIN (to_tsvector('simple', name));

-- Asset edges
CREATE TABLE edge
(
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relationship_type_id        int NOT NULL,
    rel_start                   bigint NOT NULL,
    rel_end                     bigint NOT NULL,
    data_set_id                 int NULL,
    date_created                timestamp WITH TIME ZONE,
    last_updated                timestamp WITH TIME ZONE,
    description                 text NULL,
    CONSTRAINT edge_unique_key UNIQUE (rel_start, rel_end, relationship_type_id)
);

ALTER TABLE edge
    ADD CONSTRAINT edge_relationship_type_id_fk
        FOREIGN KEY (relationship_type_id)
            REFERENCES relationship_type(id);

ALTER TABLE edge
    ADD CONSTRAINT edge_rel_start_fk
        FOREIGN KEY (rel_start)
            REFERENCES node(id);
ALTER TABLE edge
    ADD CONSTRAINT edge_rel_end_fk
        FOREIGN KEY (rel_end)
            REFERENCES node(id);

ALTER TABLE edge
    ADD CONSTRAINT edge_data_set_id_fk
        FOREIGN KEY (data_set_id)
            REFERENCES data_set(id);

CREATE INDEX edge_rel_start_idx ON edge (rel_start);
CREATE INDEX edge_rel_end_idx ON edge (rel_end);

-- Edge Metadata (Properties)
CREATE TABLE edge_metadata
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edge_id             bigint NOT NULL,
    key                 varchar(1024) NOT NULL,
    value               text NULL,
    CONSTRAINT edge_data_edge_id_fk
        FOREIGN KEY(edge_id)
            REFERENCES edge(id)
);
CREATE INDEX edge_metadata_edge_id_idx ON edge_metadata USING btree (edge_id, key, value);


-- Timeseries Data
CREATE TABLE timeseries_value_type(
  id                      bigint PRIMARY KEY,
  name                    varchar(32)
);
alter table timeseries
    add constraint timeseries_value_type_id_fk
        foreign key (value_type_id) references timeseries_value_type;

INSERT INTO timeseries_value_type VALUES
                                      (1, 'BIGINT'),
                                      (2, 'DECIMAL'),
                                      (3, 'NUMERIC'),
                                      (4, 'TEXT');

-- Timeseries Security Categories
create table timeseries_security_categories (
    timeseries_id bigint not null,
    security_categories_integer int4
);

alter table timeseries_security_categories
    add constraint timeseries_security_categories_metadata_id_fk
        foreign key (timeseries_id) references timeseries;


-- Event
CREATE TABLE event (
    id                      uuid PRIMARY KEY,
    external_id             varchar(256) not null,
    external_id_hash        bytea NOT NULL,
    type                    varchar(128),
    sub_type                varchar(128) NULL,
    description             text not null,
    data_set_id             int NOT NULL,
    source                  varchar(256),
    date_created            timestamp WITH TIME ZONE not null,
    last_updated            timestamp WITH TIME ZONE not null,
    start_time              timestamp WITH TIME ZONE not null,
    end_time                timestamp WITH TIME ZONE null
);

alter table event
    add constraint event_data_set_id_fk
        foreign key (data_set_id) references data_set;
ALTER TABLE event
    ADD CONSTRAINT event_external_id_hash_key UNIQUE (external_id_hash);
CREATE INDEX event_external_id_idx ON event USING btree (external_id);

-- Event Metadata

CREATE TABLE event_metadata
(
    id                  uuid PRIMARY KEY,
    event_id            uuid NOT NULL,
    key                 varchar(1024) NOT NULL,
    value               text NULL,
    CONSTRAINT event_metadata_event_id_fk
        FOREIGN KEY(event_id)
            REFERENCES event(id)
);
CREATE INDEX event_metadata_event_id_idx ON event_metadata USING btree (event_id, key, value);

-- Event Resources Id Collection
create table event_node_ids (
    event_id uuid not null,
    event_node_ids_long bigint NOT NULL
);
alter table event_node_ids
    add constraint event_node_ids_event_id_fk
        foreign key (event_id) references event;
CREATE INDEX event_node_ids_event_id_idx ON event_node_ids (event_id);

-- Create functions

-- This function is for working around the lack of support for ILIKE operator in Hibernate
CREATE OR REPLACE FUNCTION ILIKE_FN(name text, name_arg text) RETURNS bool
    LANGUAGE SQL
RETURN name ILIKE name_arg;

-- Stream Namespace
CREATE TABLE stream_namespace
(
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash                        bigint NOT NULL,
    name                        varchar(128) NOT NULL,
    description                 text NULL,
    backlog_quota_size          text NULL,
    backlog_quota_time          text NULL,
    retention_size              text NULL,
    retention_time              text NULL,
    date_created                timestamp WITH TIME ZONE,
    last_updated                timestamp WITH TIME ZONE,
    CONSTRAINT stream_namespace_hash_key UNIQUE (hash)
);

-- Stream Role
CREATE TABLE stream_role
(
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash                        bigint NOT NULL,
    name                        varchar(128) NOT NULL,
    description                 text NULL,
    date_created                timestamp WITH TIME ZONE,
    last_updated                timestamp WITH TIME ZONE,
    CONSTRAINT stream_role_hash_key UNIQUE (hash)
);

-- Stream Namespace permission
CREATE TABLE stream_namespace_permission
(
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namespace_id                bigint NOT NULL,
    role_id                     bigint NOT NULL,
    has_produce_permission      boolean NOT NULL DEFAULT true,
    has_consume_permission      boolean NOT NULL DEFAULT true,
    date_created                timestamp WITH TIME ZONE,
    last_updated                timestamp WITH TIME ZONE,
    CONSTRAINT stream_permission_namespace_id_fk
        FOREIGN KEY(namespace_id)
            REFERENCES stream_namespace(id),
    CONSTRAINT stream_permission_role_id_fk
        FOREIGN KEY(role_id)
            REFERENCES stream_role(id)
);
-- Stream Topic
CREATE TABLE stream_topic
(
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash                        bigint NOT NULL,
    namespace_id                bigint NOT NULL,
    partitions                  smallint NOT NULL DEFAULT 1,
    name                        varchar(128) NOT NULL,
    description                 text NULL,
    path                        text NOT NULL,
    is_persistent               boolean NOT NULL DEFAULT true,
    is_partitioned              boolean NOT NULL DEFAULT false,
    date_created                timestamp WITH TIME ZONE,
    last_updated                timestamp WITH TIME ZONE,
    CONSTRAINT stream_topic_hash_key UNIQUE (hash),
    CONSTRAINT stream_topic_namespace_id_fk
        FOREIGN KEY(namespace_id)
            REFERENCES stream_namespace(id)
);

-- Stream Topic permission
CREATE TABLE stream_topic_permission
(
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id                    bigint NOT NULL,
    role_id                     bigint NOT NULL,
    has_produce_permission      boolean NOT NULL DEFAULT true,
    has_consume_permission      boolean NOT NULL DEFAULT true,
    date_created                timestamp WITH TIME ZONE,
    last_updated                timestamp WITH TIME ZONE,
    CONSTRAINT stream_topic_permission_topic_id_fk
        FOREIGN KEY(topic_id)
            REFERENCES stream_topic(id),
    CONSTRAINT stream_permission_role_id_fk
        FOREIGN KEY(role_id)
            REFERENCES stream_role(id)
);

-- Stream Topic permission
CREATE TABLE stream_subscription
(
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id                    bigint NOT NULL,
    name                        varchar(256),
    description                 text,
    date_created                timestamp WITH TIME ZONE,
    last_updated                timestamp WITH TIME ZONE,
    CONSTRAINT stream_topic_permission_topic_id_fk
        FOREIGN KEY(topic_id)
            REFERENCES stream_topic(id)
);