CREATE TABLE cdc_connector
(
    id                              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash                            bigint NOT NULL,
    external_id                     varchar(256) NOT NULL,
    name                            varchar(512) NOT NULL,
    class_name                      text NOT NULL,
    description                     text NULL,
    date_created                    timestamp WITH TIME ZONE,
    last_updated                    timestamp WITH TIME ZONE,

    CONSTRAINT cdc_connector_hash_key UNIQUE (hash)
);

-- CDC Integration
CREATE TABLE cdc_integration
(
    id                              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash                            bigint NOT NULL,
    external_id                     varchar(256) NOT NULL,
    name                            varchar(512) NOT NULL,
    description                     text NULL,
    deactivated                     boolean NOT NULL DEFAULT true,
    date_created                    timestamp WITH TIME ZONE,
    last_updated                    timestamp WITH TIME ZONE,

    connector_id                    bigint NOT NULL,
    db_hostname                     text NOT NULL,
    db_port                         int NOT NULL,
    db_user                         text NOT NULL,
    db_password                     text NOT NULL,
    db_name                         text NOT NULL,
    topic_prefix                    text NOT NULL,
    db_plugin                       text NULL,    -- For PostgreSQL
    table_include_list              text NOT NULL,
    publication_name                text NOT NULL,
    publication_autocreate_mode     text NOT NULL DEFAULT 'filtered',
    offset_storage                  text NOT NULL DEFAULT 'org.apache.kafka.connect.storage.FileOffsetBackingStore',
    offset_storage_filename         text NOT NULL,
    offset_flush_interval_ms        int NOT NULL DEFAULT 6000,
    snapshot_mode                   TEXT NOT NULL DEFAULT 'initial',

    CONSTRAINT cdc_integration_hash_key UNIQUE (hash),
    CONSTRAINT cdc_integration_connector_id_fk
        FOREIGN KEY(connector_id)
            REFERENCES cdc_connector(id)
);
