-- Naming policy: the near-duplicate index and the findings table.
--
-- Both halves of this migration exist because external ids are about to be stored verbatim
-- (`VAL-21-PT-1034`, `=K1-M3+B02`) instead of being rewritten to snake_case. Relaxing the charset
-- removes the accidental protection the old rewrite gave, so the two things that replace it —
-- a near-duplicate guard and a durable record of what the guard let through — are added here
-- together.

-- ---------------------------------------------------------------------------------------------
-- 1. Near-duplicate folding index
-- ---------------------------------------------------------------------------------------------
--
-- Uniqueness itself is unchanged: it stays on node.external_id_hash, which now hashes the
-- LOWERCASED external id, so `VAL-01` and `val-01` collide on the existing unique constraint with
-- no DDL at all. This index covers the fuzzier case that hashing cannot: ids that differ only in
-- which separator was typed. `pump-a-01`, `pump.a.01` and `pump_a_01` all fold to `pump_a_01`, so
-- a lookup on the folded value finds the near-duplicate that already exists.
--
-- Deliberately NOT UNIQUE. The guard has two modes (`reject` and `warn`) and is configured per
-- tenant, so enforcement has to live in application code — a unique index would make the `warn`
-- mode unimplementable, and would also mean a policy change could not be rolled back without DDL.
-- This index only makes the lookup an index scan instead of a sequential scan over every node.
--
-- The translate() set is exactly the separator characters the relaxed charset admits
-- (`- . : + =`); everything else in the charset is alphanumeric or `_`. Keep the two in step: a
-- character added to the charset without being added here is a separator the guard cannot see.
-- The expression must be written identically at the query site or Postgres will not use the index.
CREATE INDEX node_external_id_folded_idx
    ON node (lower(translate(external_id, '-.:+=', '_____')));

-- ---------------------------------------------------------------------------------------------
-- 2. policy_finding
-- ---------------------------------------------------------------------------------------------
--
-- A policy can return WARNING as well as OK and NOT_OK: "allowed, and someone should look at it".
-- That middle verdict is only meaningful if it is durable and queryable, which is what this table
-- is. The cheaper option — writing the warning into the entity's `metadata` map — was rejected
-- because `metadata` is a user-editable Map<String,String>, so the caller who triggered a finding
-- could silently delete or forge it. That is a note, not a record.
--
-- Only WARNING is persisted. NOT_OK rejects the write, so there is no entity to hang a finding on;
-- a log of *rejected attempts* is a different thing (keyed on the caller, not the entity) and is
-- out of scope.
--
-- `text` rather than `varchar(n)` throughout. In PostgreSQL the two are stored and perform
-- identically and `varchar(n)` only adds a length check, which is worth having when it states a
-- real domain rule and is noise otherwise. Every value here is either generated by us (`message`,
-- `suggestion`) or already bounded by the validation at its source (`policy_name`,
-- `offending_value`), so a cap here would restate a rule that lives elsewhere and then drift from
-- it. `raised_by` especially: it is an identity-provider subject, and guessing a maximum for
-- something another system issues is how you get a truncation bug on the one deployment whose
-- subjects are longer than you assumed.
CREATE TABLE policy_finding (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ON DELETE CASCADE: findings retire with the entity they are about. A queue listing
    -- complaints about resources that no longer exist is a queue nobody reads.
    node_id         bigint NOT NULL REFERENCES node(id) ON DELETE CASCADE,

    -- Policies are themselves nodes and can be deleted. The FK goes to SET NULL rather than
    -- CASCADE, and `policy_name` below is denormalised beside it, so a finding whose policy has
    -- since been deleted still says what fired instead of becoming an anonymous complaint.
    policy_id       bigint REFERENCES node(id) ON DELETE SET NULL,
    policy_name     text   NOT NULL,

    message         text   NOT NULL,
    suggestion      text,

    -- The value that tripped the policy, kept so re-evaluation can tell "same problem as before"
    -- from "the id changed and this is a new problem". The upsert compares against it to decide
    -- whether a resolved finding reopens; see PolicyFindingRepository.
    offending_value text   NOT NULL,

    -- JWT `sub` of whoever created the entity, so a steward can go back to the integration that
    -- produced the value rather than guessing.
    raised_by       text,

    -- The only DEFAULT now() in this schema, and deliberately so. Every other table gets its
    -- timestamp from Hibernate's @CreationTimestamp, where a DB default would be dead code:
    -- Hibernate puts its own value in every INSERT, so the default never fires and only reads
    -- like a guarantee. This table is written by a native INSERT ... ON CONFLICT (JPA has no
    -- natural upsert), so there is no Hibernate value and the default is what actually runs.
    --
    -- Second reason, which outlives the first: several api instances serve writes, each with its
    -- own clock. An application timestamp would order the steward's queue by whichever instance
    -- happened to take the request. now() is one clock.
    date_created    timestamp WITH TIME ZONE NOT NULL DEFAULT now(),

    -- NULL = open. Set when a steward judges the violation acceptable. Note this is a judgement,
    -- not a fix: the entity still violates the policy.
    resolved_at     timestamp WITH TIME ZONE,

    -- A finding is the CURRENT verdict for one entity under one policy, not an append-only log of
    -- every time that entity was checked. Re-evaluating (on update, re-create, or a policy change)
    -- upserts onto this key, so a resource checked a thousand times still has one row.
    CONSTRAINT policy_finding_node_policy_key UNIQUE (node_id, policy_name)
);

-- The steward's queue is "open findings for this policy, oldest first", so index exactly that.
-- Partial on resolved_at IS NULL: resolved rows are the ones that accumulate (nothing prunes them
-- yet) and the queue never reads them, so keeping them out of the index keeps it proportional to
-- the work outstanding rather than to the table.
CREATE INDEX policy_finding_open_idx
    ON policy_finding (policy_name, date_created) WHERE resolved_at IS NULL;
