-- Directory
CREATE TABLE directory
(
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id         bigint NULL,
    path_hash         bigint NOT NULL,
    data_set_id       int NULL,
    name              varchar(512) NOT NULL,
    path              text NOT NULL,
    description       text NULL,
    date_created      timestamp WITH TIME ZONE,
    last_updated      timestamp WITH TIME ZONE,
    CONSTRAINT directory_path_hash_key UNIQUE (path_hash),
    CONSTRAINT directory_parent_id_fk
        FOREIGN KEY(parent_id)
            REFERENCES directory(id),
    CONSTRAINT directory_data_set_id_fk
        FOREIGN KEY (data_set_id) REFERENCES data_set
);
-- End Directory

-- File
CREATE TABLE file
(
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    directory_id            bigint NULL,
    external_id             varchar(256) NOT NULL,
    external_id_hash        bigint NOT NULL,
    data_set_id             int NULL,
    name                    varchar(512) NOT NULL,
    description             text NULL,
    mime_type               text NULL,
    source                  text NULL,
    labels                  text NULL,
    source_date_created     timestamp WITH TIME ZONE,
    source_last_updated     timestamp WITH TIME ZONE,
    date_created            timestamp WITH TIME ZONE,
    last_updated            timestamp WITH TIME ZONE,
    CONSTRAINT file_external_id_hash_key UNIQUE (external_id_hash),
    CONSTRAINT file_data_set_id_fk
        FOREIGN KEY (data_set_id) REFERENCES data_set
);
-- Btree is better for exact matches and pattern matching at the beginning of strings
CREATE INDEX file_external_id_idx ON data_set USING btree (external_id);
CREATE INDEX file_directory_id_idx ON file USING btree (directory_id);
CREATE INDEX file_name_idx ON data_set USING GIN (to_tsvector('simple', name));
-- End File

-- File Metadata
CREATE TABLE file_metadata
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id             bigint NOT NULL,
    key                 varchar(1024) NOT NULL,
    value               text NULL,
    CONSTRAINT file_metadata_file_id_fk
        FOREIGN KEY(file_id)
            REFERENCES file(id)
);
-- End File Metadata

-- File Resources Id Collection
create table file_node_ids (
                                file_id bigint not null,
                                file_node_ids_long bigint NOT NULL
);
alter table file_node_ids
    add constraint file_node_ids_file_id_fk
        foreign key (file_id) references file;
CREATE INDEX file_node_ids_file_id_idx ON file_node_ids (file_id);
-- End File Resources Id Collection

-- File Labels Many to Many
CREATE TABLE file_labels(
                            file_id bigint NOT NULL REFERENCES file(id),
                            label_id bigint NOT NULL REFERENCES label(id)
);
CREATE INDEX file_labels_file_id_idx ON file_labels USING btree (file_id, label_id);
-- End File Labels

-- File Security Categories
create table file_security_categories (
            file_id bigint not null,
            security_categories_integer int4
);

alter table file_security_categories
    add constraint file_security_categories_id_fk
        foreign key (file_id) references file;
-- End File Security Categories