-- Transactional outbox for the Postgres -> Neo4j graph mirror.
--
-- Before this table, a resource change was mirrored by publishing to Pulsar *after* the JPA
-- transaction committed: a crash in that window lost the graph update permanently, and a
-- consumer that failed ten times dropped the message and left the mirror silently diverged.
-- A row here is written INSIDE the same transaction as the node/edge change, so the intent to
-- sync commits or rolls back with the data it describes. datahub-api drains the queue right
-- after commit and re-drains anything outstanding on a timer, so every committed change
-- reaches the graph eventually, in order, across crashes.
--
-- One table per tenant database (tenants are separate databases, not schemas), so there is no
-- tenant column; the routing datasource already picks the right database.
CREATE TABLE resource_outbox (
    -- Identity rather than a sequence default: the drain reads strictly in id order, and this
    -- is the only ordering the applier relies on.
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The sync command: which node and edge ids to re-mirror, and which to delete. Deliberately
    -- NOT a snapshot of the entity — the applier reads current state from Postgres at drain
    -- time, so a replayed row writes today's state instead of resurrecting yesterday's. jsonb
    -- (not text) so the payload stays queryable when diagnosing a stalled queue.
    payload         jsonb NOT NULL,

    -- now() as a column default, matching naming_policy_findings (V32) and for the same two
    -- reasons: rows are written by native inserts as well as Hibernate, and several api
    -- instances with drifting clocks must not decide queue order between them.
    created_at      timestamp WITH TIME ZONE NOT NULL DEFAULT now(),

    -- NULL means pending. Applied rows are kept for a few days as an audit trail, then purged.
    applied_at      timestamp WITH TIME ZONE,

    -- Retry bookkeeping, durable on purpose: an api restart must not reset a failing row's
    -- backoff, and `attempts` + `last_error` are how an operator diagnoses a stalled tenant.
    attempts        int NOT NULL DEFAULT 0,
    next_attempt_at timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    last_error      text
);

-- The drain asks one question — "oldest pending rows?" — and the sweep asks a cheaper version
-- of it ("any pending at all?"). A partial index keeps both off the applied rows, which are the
-- overwhelming majority. Indexed on id alone because the queue is strictly head-of-line: the
-- oldest pending row's next_attempt_at gates the whole tenant, so there is nothing to gain from
-- ordering by the retry timestamp.
CREATE INDEX resource_outbox_pending_idx ON resource_outbox (id) WHERE applied_at IS NULL;
