-- Agent definitions: what an LLM agent is called, what it is told, which model backend it uses,
-- and — the point of the table — exactly which MCP tools it may be offered.
--
-- Before this table there was one hard-wired assistant. Its prompt came from a deployment-wide
-- Vault field and its tool list was a hardcoded set of twenty names compiled into datahub-console,
-- identical for every tenant and every user. A customer could not give the assistant their own
-- vocabulary, could not narrow what it may look at, and could not have a second assistant scoped
-- to something different. All three are the same missing concept: an agent.
--
-- WHAT LIVES HERE AND WHAT LIVES IN VAULT
-- A tenant's `llm-backends` Vault block says which model an agent may use and how to reach it —
-- provider, credential, base url. It holds secrets, so it stays in Vault. This table says what to
-- do with that model: the prompt, the tools, and how much to spend per turn. Those are not
-- secrets, they are edited far more often, and they differ per agent while a backend is shared,
-- so they belong in the tenant's own database where a change is a transaction and not a secret
-- rotation. `backend_ref` is the join between the two, by name.
--
-- ONE TABLE PER TENANT DATABASE
-- Tenants are separate databases, not schemas, so there is no tenant column — the routing
-- datasource already picks the right database. Same reasoning as V42__resource_outbox.sql.
--
-- WHAT IS DELIBERATELY ABSENT
-- Nothing here describes an agent that runs on its own: no mode, no trigger, no identity to run
-- as, no run history. Those are real and coming, but their shape is not yet known, and a column
-- nobody writes is worse than a migration nobody has written yet — it reads as a contract while
-- guaranteeing nothing. An agent today runs when a signed-in person asks it to, as that person.
CREATE TABLE agent (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Stable name an operator and an API client both refer to the agent by, e.g.
    -- 'console-assistant'. Unique per tenant, which is per database, so a plain UNIQUE.
    external_id       text NOT NULL UNIQUE,

    -- Shown to people. Free text, and expected to be translated by the caller, not here.
    display_name      text NOT NULL,

    -- Names an entry in the tenant's Vault `llm-backends` block. NULL means the deployment-wide
    -- default backend, which is what every tenant used before this table existed. A name that no
    -- longer exists in Vault is treated the same way, so deleting a backend degrades the agents
    -- using it to the default rather than breaking them.
    backend_ref       text,

    -- Appended to the built-in system prompt — domain vocabulary, tag conventions, what this
    -- customer cares about. Appended and never substituted, so the tool discipline and the
    -- read-only framing in the built-in prompt cannot be configured away from here.
    instructions      text,

    -- The explicit list. Default-deny: a tool not named here is never offered to the model, and
    -- an empty list means an agent with no tools, not an agent with all of them. Validated on
    -- write against the platform's tool catalogue, so a typo is rejected rather than silently
    -- becoming a tool the agent does not have.
    --
    -- This is only half of what the agent may actually do. The other half is the permissions of
    -- whoever it runs as, applied per request; the two intersect, and neither can widen the
    -- other. Enforcement itself remains where it has always been — in the api services that
    -- perform each read and write.
    tool_allowlist    text[] NOT NULL DEFAULT '{}',

    -- COST CONTROLS. Per agent rather than per backend, because one backend serves several
    -- agents that should not be forced to share a budget, and because these are dials an
    -- operator wants to turn without touching a secret store.

    -- Where the effort picker starts for a new user: 'low' | 'medium' | 'high' | 'xhigh' | 'max'.
    -- Only the starting point — effort is a per-message choice and the picker keeps overriding
    -- this. NULL leaves the deployment default in place.
    default_effort    text,

    -- Ceiling on one call's output. NULL lets the effort level choose, which rises with depth
    -- because the ceiling caps thinking and answer together. Set, it is obeyed at every level, so
    -- a roof an operator wrote down beats a level a user clicked: the cost of that is truncation,
    -- which is visible, rather than a surprising bill, which is not.
    max_output_tokens integer,

    -- Ceiling on model->tool->model round trips in one turn. Bounds both cost and latency. NULL
    -- takes the deployment default.
    max_iterations    integer,

    -- Off means the agent is not offered and will not answer, without losing its definition.
    enabled           boolean NOT NULL DEFAULT true,

    -- now() as column defaults, matching resource_outbox (V42) and naming_policy_findings (V32):
    -- rows are written by native inserts as well as Hibernate, and several api instances with
    -- drifting clocks must not disagree about ordering.
    created_at        timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at        timestamp WITH TIME ZONE NOT NULL DEFAULT now()
);

-- The console assistant, as it behaved before this table existed. The allowlist is the exact
-- twenty read-only tool names that were hardcoded in datahub-console's ToolPolicy, and every
-- cost column is NULL so the deployment defaults keep supplying the values they already did.
-- Seeding it here rather than in application code means an upgraded tenant answers the first
-- request after the migration exactly as it answered the last one before it.
--
-- This row is the tenant's to edit from here on: narrowing the list, adding instructions or
-- pointing it at their own backend is expected, and nothing overwrites it later.
INSERT INTO agent (external_id, display_name, tool_allowlist)
VALUES (
    'console-assistant',
    'Console assistant',
    ARRAY[
        'analysis_related_series',
        'dataset_list',
        'dataset_search',
        'edge_get',
        'edge_list_types',
        'event_filter',
        'event_get',
        'event_search',
        'label_list',
        'resource_fetch_nearest',
        'resource_fetch_related',
        'resource_get',
        'resource_search',
        'timeseries_fetch_datapoints',
        'timeseries_get',
        'timeseries_get_latest',
        'timeseries_list',
        'timeseries_search',
        'unit_get',
        'unit_list'
    ]
);
