-- Unit
CREATE TABLE unit (
                            id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name                    varchar(64) NOT NULL,
                            description             text NULL,
                            external_id             varchar(256) NOT NULL,
                            external_id_hash        bigint NOT NULL,
                            long_name               varchar(256) NULL,
                            symbol                  varchar(32) NULL,
                            quantity                text NULL,
                            source                  text NULL,
                            source_reference        text NULL,
                            conversion_multiplier   decimal NULL,
                            conversion_offset       decimal NULL
);

create table unit_alias_names (
    unit_id bigint not null,
    alias_names_text text
);
alter table unit_alias_names
    add constraint unit_alias_names_unit_id_fk
        foreign key (unit_id) references unit;

-- Celsius
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
       'DEG_C',
       'The unit celsius, also known as centigrade, is a scale and unit of measurement for temperature. It can refer to a specific temperature on the Celsius scale as well as a unit to indicate a temperature interval, a difference between two temperatures or an uncertainty. This definition fixes the magnitude of both the degree Celsius and the kelvin as precisely 1 part in 273.16 (approximately 0.00366) of the difference between absolute zero and the triple point of water. Thus, it sets the magnitude of one degree Celsius and that of one kelvin as exactly the same. Additionally, it establishes the difference between the two scales null points as being precisely 273.15',
       'temperature_deg_c',
       -3782741072842069489,
       'degree Celsius',
       '°C',
       'Temperature',
       'qudt.org',
       'https://qudt.org/vocab/unit/DEG_C',
       1,
       273.15
);
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, '°C' FROM unit WHERE external_id_hash = -3782741072842069489
UNION ALL
    SELECT id, 'C' FROM unit WHERE external_id_hash = -3782741072842069489
UNION ALL
    SELECT id, 'deg C' FROM unit WHERE external_id_hash = -3782741072842069489
UNION ALL
    SELECT id, 'degC' FROM unit WHERE external_id_hash = -3782741072842069489
UNION ALL
    SELECT id, 'DegC' FROM unit WHERE external_id_hash = -3782741072842069489
;

-- Kilowatt per hour
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'KiloW-HR',
          'The kilowatt hour, or kilowatt-hour, (symbol $kW \\cdot h$, $kW h$ or $kWh$) is a unit of energy equal to 1000 watt hours or 3.6 megajoules. For constant power, energy in watt hours is the product of power in watts and time in hours. The kilowatt hour is most commonly known as a billing unit for energy delivered to consumers by electric utilities.',
          'energy_kw_hr',
          -998330685076066191,
          'Kilowatthour',
          'kW·hr',
          'Energy',
          'qudt.org',
          'https://qudt.org/vocab/unit/KiloW-HR',
          3600000,
          0
);
INSERT INTO unit_alias_names(unit_id, alias_names_text)
       SELECT id, 'kwh' FROM unit WHERE external_id_hash = -998330685076066191
UNION ALL
       SELECT id, 'kw-H' FROM unit WHERE external_id_hash = -998330685076066191
UNION ALL
       SELECT id, 'kw-h' FROM unit WHERE external_id_hash = -998330685076066191
UNION ALL
       SELECT id, 'KW-H' FROM unit WHERE external_id_hash = -998330685076066191
UNION ALL
       SELECT id, 'KW-hr' FROM unit WHERE external_id_hash = -998330685076066191
UNION ALL
       SELECT id, 'kw-hr' FROM unit WHERE external_id_hash = -998330685076066191
UNION ALL
       SELECT id, 'KW/h' FROM unit WHERE external_id_hash = -998330685076066191
UNION ALL
       SELECT id, 'KW/H' FROM unit WHERE external_id_hash = -998330685076066191
UNION ALL
       SELECT id, 'kw/h' FROM unit WHERE external_id_hash = -998330685076066191
;

-- BAR
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'BAR',
          'The bar is a unit of pressure defined as 100 000 pascal.',
          'pressure_bar',
          1787746705356450747,
          'BAR',
          'bar',
          'Pressure',
          'qudt.org',
          'https://qudt.org/vocab/unit/BAR',
          100000,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'bar' FROM unit WHERE external_id_hash = 1787746705356450747
UNION ALL
    SELECT id, 'BAR' FROM unit WHERE external_id_hash = 1787746705356450747
;

-- BQ-PER-M3
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'BQ-PER-M3',
          'Becquerel Per Cubic Meter (Bq/m3) is a unit in the category of Radioactivity concentration. It is also known as becquerels per cubic meter, becquerel per cubic metre, becquerels per cubic metre, becquerel/cubic inch. This unit is commonly used in the SI unit system. Becquerel Per Cubic Meter (Bq/m3) has a dimension of L-3T-1 where L is length, and T is time. It essentially the same as the corresponding standard SI unit /s-m3.',
          'concentration_bq_m3',
          5190404385214492463,
          'Becquerel per Cubic Meter',
          'Bq/m3',
          'Concentration',
          'qudt.org',
          'https://qudt.org/vocab/unit/BQ-PER-M3',
          1,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'Bq/m3' FROM unit WHERE external_id_hash = 5190404385214492463
UNION ALL
    SELECT id, 'Bq.m-3' FROM unit WHERE external_id_hash = 5190404385214492463
UNION ALL
    SELECT id, 'BQ-M3' FROM unit WHERE external_id_hash = 5190404385214492463
;

-- PPM
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'PPM',
          'Dimensionless unit for concentration.',
          'concentration_ppm',
          3415007738012226786,
          'Parts per million',
          'PPM',
          'Concentration',
          'qudt.org',
          'https://qudt.org/vocab/unit/PPM',
          0.000001,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'PPM' FROM unit WHERE external_id_hash = 3415007738012226786
UNION ALL
    SELECT id, 'ppm' FROM unit WHERE external_id_hash = 3415007738012226786
;

-- PPB
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'PPB',
          'Dimensionless unit for concentration.',
          'concentration_ppb',
          -6177565474067393302,
          'Parts per billion',
          'PPB',
          'Concentration',
          'qudt.org',
          'https://qudt.org/vocab/unit/PPB',
          0.000000001,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'PPB' FROM unit WHERE external_id_hash = -6177565474067393302
UNION ALL
    SELECT id, 'ppb' FROM unit WHERE external_id_hash = -6177565474067393302
;

-- Percent
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Percent',
          '"Percent" is a unit for Dimensionless Ratio',
          'concentration_percent',
          -2944233797172920539,
          'Percent',
          '%',
          'Concentration',
          'qudt.org',
          'https://qudt.org/vocab/unit/PERCENT',
          0.01,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'PERCENT' FROM unit WHERE external_id_hash = -2944233797172920539
UNION ALL
    SELECT id, 'percent' FROM unit WHERE external_id_hash = -2944233797172920539
UNION ALL
    SELECT id, 'per cent' FROM unit WHERE external_id_hash = -2944233797172920539
UNION ALL
    SELECT id, 'per-cent' FROM unit WHERE external_id_hash = -2944233797172920539
;

-- Pascal
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Pascal',
          'The SI unit of pressure. The pascal is the standard pressure unit in the MKS metric system, equal to one newton per square meter or one "kilogram per meter per second per second." The unit is named for Blaise Pascal (1623-1662), French philosopher and mathematician, who was the first person to use a barometer to measure differences in altitude.',
          'pressure_pa',
          -4133141888317534630,
          'Pascal',
          'Pa',
          'Pressure',
          'qudt.org',
          'https://qudt.org/vocab/unit/PA',
          1,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'Pa' FROM unit WHERE external_id_hash = -4133141888317534630
UNION ALL
    SELECT id, 'pascal' FROM unit WHERE external_id_hash = -4133141888317534630
UNION ALL
    SELECT id, 'Pascal' FROM unit WHERE external_id_hash = -4133141888317534630
;

-- Square Metre
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Square Meter (m2)',
          'The S I unit of area is the square metre.',
          'area_m2',
          8254024452978253676,
          'Square Meter',
          'm²',
          'Area',
          'qudt.org',
          'https://qudt.org/vocab/unit/M2',
          1,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'm2' FROM unit WHERE external_id_hash = 8254024452978253676
UNION ALL
    SELECT id, 'M2' FROM unit WHERE external_id_hash = 8254024452978253676
UNION ALL
    SELECT id, 'MTK' FROM unit WHERE external_id_hash = 8254024452978253676
;

-- Cubic Metre
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Cubic Meter (m3)',
          'The SI unit of volume, equal to 1.0e6 cm3, 1000 liters, 35.3147 ft3, or 1.30795 yd3. A cubic meter holds about 264.17 U.S. liquid gallons or 219.99 British Imperial gallons.',
          'volume_m3',
          8254024452978253676,
          'Cubic Meter',
          'm³',
          'Volume',
          'qudt.org',
          'https://qudt.org/vocab/unit/M3',
          1,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'm3' FROM unit WHERE external_id_hash = 8254024452978253676
UNION ALL
    SELECT id, 'M3' FROM unit WHERE external_id_hash = 8254024452978253676
UNION ALL
    SELECT id, 'MTQ' FROM unit WHERE external_id_hash = 8254024452978253676
;

-- Cubic Metre per hour
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Cubic Meter Per Hour (m3/h)',
          'Cubic Meter Per Hour (m3/h) has a dimension of L3T-1 where is length, and is time. It can be converted to the corresponding standard SI unit m3/s by multiplying its value by a factor of 0.00027777777. Cubic Meter Per Hour (m3/h) is a unit in the category of Volume flow rate.',
          'volume_flow_rate_m3',
          -6146356312642752776,
          'Cubic Meter Per Hour',
          'm³/hr',
          'Volume Flow Rate',
          'qudt.org',
          'https://qudt.org/vocab/unit/M3-PER-HR',
          0.0002777777777777778,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'm3/hr' FROM unit WHERE external_id_hash = -6146356312642752776
UNION ALL
    SELECT id, 'm3/hour' FROM unit WHERE external_id_hash = -6146356312642752776
UNION ALL
    SELECT id, 'm³/hr' FROM unit WHERE external_id_hash = -6146356312642752776
UNION ALL
    SELECT id, 'm³/hour' FROM unit WHERE external_id_hash = -6146356312642752776
UNION ALL
    SELECT id, 'M3-hr' FROM unit WHERE external_id_hash = -6146356312642752776
UNION ALL
    SELECT id, 'm3/h' FROM unit WHERE external_id_hash = -6146356312642752776
UNION ALL
    SELECT id, 'MQH' FROM unit WHERE external_id_hash = -6146356312642752776
;

-- Litre per hour
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Liter per Hour',
          'Unit litre divided by the unit hour.',
          'volume_flow_rate_litre',
          -9130818569199765900,
          'Liter per Hour',
          'L/hr',
          'Volume Flow Rate',
          'qudt.org',
          'https://qudt.org/vocab/unit/L-PER-HR',
          0.0000002777778,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'L/hr' FROM unit WHERE external_id_hash = -9130818569199765900
UNION ALL
    SELECT id, 'l-hour³' FROM unit WHERE external_id_hash = -9130818569199765900
UNION ALL
    SELECT id, 'l/h' FROM unit WHERE external_id_hash = -9130818569199765900
UNION ALL
    SELECT id, 'L/h' FROM unit WHERE external_id_hash = -9130818569199765900
;

-- Kilogram Per Hour
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Kilogram Per Hour',
          'Kilogram Per Hour (kg/h) is a unit in the category of Mass flow rate. It is also known as kilogram/hour. Kilogram Per Hour (kg/h) has a dimension of MT-1 where M is mass, and T is time. It can be converted to the corresponding standard SI unit kg/s by multiplying its value by a factor of 0.000277777777778.',
          'mass_flow_rate_kghr',
          -857679344454260352,
          'Kilogram Per Hour',
          'kg/hr',
          'Mass Flow Rate',
          'qudt.org',
          'https://qudt.org/vocab/unit/KiloGM-PER-HR',
          0.000277777778,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'kg/h' FROM unit WHERE external_id_hash = -857679344454260352
UNION ALL
    SELECT id, 'kg/hour' FROM unit WHERE external_id_hash = -857679344454260352
UNION ALL
    SELECT id, 'kg-h' FROM unit WHERE external_id_hash = -857679344454260352
UNION ALL
    SELECT id, 'kg-hour' FROM unit WHERE external_id_hash = -857679344454260352
;

-- Watt
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Watt',
          'The SI unit of power. Power is the rate at which work is done, or (equivalently) the rate at which energy is expended. One watt is equal to a power rate of one joule of work per second of time. This unit is used both in mechanics and in electricity, so it links the mechanical and electrical units to one another. In mechanical terms, one watt equals about 0.001 341 02 horsepower (hp) or 0.737 562 foot-pound per second (lbf/s). In electrical terms, one watt is the power produced by a current of one ampere flowing through an electric potential of one volt. The name of the unit honors James Watt (1736-1819), the British engineer whose improvements to the steam engine are often credited with igniting the Industrial Revolution.',
          'power_watt',
          -5130324094273505406,
          'Watt',
          'W',
          'Power',
          'qudt.org',
          'https://qudt.org/vocab/unit/W',
          1,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'watt' FROM unit WHERE external_id_hash = -5130324094273505406
UNION ALL
    SELECT id, 'Watt' FROM unit WHERE external_id_hash = -5130324094273505406
UNION ALL
    SELECT id, 'w' FROM unit WHERE external_id_hash = -5130324094273505406
;

-- Voltage
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Volt',
          'Volt is the SI unit of electric potential. Separating electric charges creates potential energy, which can be measured in energy units such as joules. Electric potential is defined as the amount of potential energy present per unit of charge. Electric potential is measured in volts, with one volt representing a potential of one joule per coulomb of charge.',
          'electric_potential_volt',
          -2560725459965144719,
          'Watt',
          'V',
          'Electric Potential',
          'qudt.org',
          'https://qudt.org/vocab/unit/V',
          1,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'volt' FROM unit WHERE external_id_hash = -2560725459965144719
UNION ALL
    SELECT id, 'Volt' FROM unit WHERE external_id_hash = -2560725459965144719
UNION ALL
    SELECT id, 'v' FROM unit WHERE external_id_hash = -2560725459965144719
;

-- Electronvolt
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Electronvolt',
          'In physics, an electronvolt (symbol eV), also written electron-volt and electron volt, is the measure of an amount of kinetic energy gained by a single electron accelerating through an electric potential difference of one volt in vacuum. When used as a unit of energy, the numerical value of 1 eV in joules (symbol J) is equal to the numerical value of the charge of an electron in coulombs (symbol C). Under the 2019 redefinition of the SI base units, this sets 1 eV equal to the exact value 1.602176634×10−19 J.',
          'energy_ev',
          4877496328376127645,
          'Electronvolt',
          'eV',
          'Energy',
          'qudt.org',
          'https://qudt.org/vocab/unit/EV',
          0.0000000000000000001602176634,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'A53' FROM unit WHERE external_id_hash = 4877496328376127645
UNION ALL
       SELECT id, 'ev' FROM unit WHERE external_id_hash = 4877496328376127645
UNION ALL
       SELECT id, 'EV' FROM unit WHERE external_id_hash = 4877496328376127645
;

-- Calorie
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Calorie',
          'The energy needed to increase the temperature of a given mass of water by 1 Celsius at atmospheric pressure depends on the starting temperature and is difficult to measure precisely. Accordingly, there have been several definitions of the calorie. The two perhaps most popular definitions used in older literature are the calorie and the 15 Celsius thermochemical calorie.',
          'energy_thermochemical_calorie',
          2737737462797223137,
          'Thermochemical Calorie',
          'cal',
          'Energy',
          'qudt.org',
          'https://qudt.org/vocab/unit/CAL_TH',
          4.184,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'calorie' FROM unit WHERE external_id_hash = 2737737462797223137
UNION ALL
    SELECT id, 'cal_th' FROM unit WHERE external_id_hash = 2737737462797223137
;

-- Kilogram
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Kilogram',
          'The kilogram or kilogramme (SI symbol: kg), also known as the kilo, is the base unit of mass in the International System of Units and is defined as being equal to the mass of the International Prototype Kilogram (IPK), which is almost exactly equal to the mass of one liter of water. The avoirdupois (or international) pound, used in both the Imperial system and U.S. customary units, is defined as exactly 0.45359237 kg, making one kilogram approximately equal to 2.2046 avoirdupois pounds.',
          'mass_kilogram',
          119496760167918124,
          'Kilogram',
          'kg',
          'Mass',
          'qudt.org',
          'https://qudt.org/vocab/unit/KiloGM',
          1,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'KG' FROM unit WHERE external_id_hash = 119496760167918124
UNION ALL
    SELECT id, 'KGM' FROM unit WHERE external_id_hash = 119496760167918124
;

-- Ampere
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Ampere',
          'The ampere is a measure of the amount of electric charge in motion per unit time ― that is, electric current. But the quantity of electric charge by itself, whether in motion or not, is expressed by another SI unit, the coulomb (C). One coulomb is equal to about 6.241 x 1018 electric charges (e).',
          'current_ampere',
          5589698192129408235,
          'Ampere',
          'A',
          'Current',
          'qudt.org',
          'https://qudt.org/vocab/unit/A',
          1,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'ampere' FROM unit WHERE external_id_hash = 5589698192129408235
UNION ALL
    SELECT id, 'amperium' FROM unit WHERE external_id_hash = 5589698192129408235
;

-- Mole
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Mole',
          'The ampere is a measure of the amount of electric charge in motion per unit time ― that is, electric current. But the quantity of electric charge by itself, whether in motion or not, is expressed by another SI unit, the coulomb (C). One coulomb is equal to about 6.241 x 1018 electric charges (e).',
          'amounts_chemical_substance_mole',
          2704904531428955691,
          'Mole',
          'mol',
          'Amounts of a chemical substance',
          'qudt.org',
          'https://qudt.org/vocab/unit/MOL',
          1,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'MOL' FROM unit WHERE external_id_hash = 2704904531428955691
UNION ALL
    SELECT id, 'mole' FROM unit WHERE external_id_hash = 2704904531428955691
;

-- Barrel
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Barrel UK petroleum',
          'Unit of the volume for crude oil according to the Imperial system of units.',
          'volume_barrel_pet_uk',
          -4037223475039966815,
          'Barrel (UK Petroleum)',
          'bbl{UK petroleum}',
          'Volume',
          'qudt.org',
          'https://qudt.org/vocab/unit/BBL_UK_PET',
          0.1591132,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'bbl' FROM unit WHERE external_id_hash = -4037223475039966815
UNION ALL
    SELECT id, 'bbl-uk' FROM unit WHERE external_id_hash = -4037223475039966815
UNION ALL
    SELECT id, 'bbl_uk' FROM unit WHERE external_id_hash = -4037223475039966815
;

-- Barrel
INSERT INTO unit(name, description, external_id, external_id_hash, long_name, symbol,
                 quantity, source, source_reference, conversion_multiplier, conversion_offset)
VALUES(
          'Barrel US petroleum',
          'Unit of the volume for crude oil according to the Anglo-American system of units.',
          'volume_barrel_pet_us',
          8043982325957282230,
          'Barrel (US)',
          'bbl{US petroleum}',
          'Volume',
          'qudt.org',
          'https://qudt.org/vocab/unit/BBL_US',
          0.1589873,
          0
      );
INSERT INTO unit_alias_names(unit_id, alias_names_text)
    SELECT id, 'bbl' FROM unit WHERE external_id_hash = 8043982325957282230
UNION ALL
    SELECT id, 'bbl-us' FROM unit WHERE external_id_hash = 8043982325957282230
UNION ALL
    SELECT id, 'bbl_us' FROM unit WHERE external_id_hash = 8043982325957282230
;