CREATE TABLE inodes(
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id             varchar(256) NOT NULL,
    external_id_hash        bigint NOT NULL,
    parent_id               bigint NULL,
    data_set_id             int NULL,
    is_deleted              bool NOT NULL,
    name                    varchar(512) NOT NULL,
    description             text NULL,
    size                    bigint NULL,
    checksum                bytea NULL,
    node_type               smallint NOT NULL,
    mime_type               text NULL,
    source                  text NULL,
    labels                  text NULL,
    path                    text NOT NULL,
    path_hash               bigint NOT NULL,
    target_path             text NULL,
    target_path_hash        bigint NULL,
    source_date_created     timestamp WITH TIME ZONE,
    source_last_updated     timestamp WITH TIME ZONE,
    date_created            timestamp WITH TIME ZONE,
    last_updated            timestamp WITH TIME ZONE,
    CONSTRAINT inode_external_id_hash_key UNIQUE (external_id_hash),
    CONSTRAINT inode_data_set_id_fk
       FOREIGN KEY (data_set_id) REFERENCES data_set
);

-- Btree is better for exact matches and pattern matching at the beginning of strings
CREATE INDEX inodes_external_id_idx ON inodes USING btree (external_id);
CREATE INDEX inodes_path_hash_idx ON inodes USING btree (path_hash);
CREATE INDEX inodes_parent_id_idx ON inodes USING btree (parent_id);
CREATE INDEX inodes_is_deleted_idx ON inodes USING btree (is_deleted);
CREATE INDEX inodes_name_idx ON inodes USING GIN (to_tsvector('simple', name));

-- Inode Metadata
CREATE TABLE inode_metadata
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inode_id            bigint NOT NULL,
    key                 varchar(1024) NOT NULL,
    value               text NULL,
    CONSTRAINT inode_metadata_inode_id_fk
        FOREIGN KEY(inode_id)
            REFERENCES inodes(id)
);

-- Inode Resources Id Collection
create table inode_related_resources (
    inode_id bigint not null,
    resource_id bigint NOT NULL
);
alter table inode_related_resources
    add constraint inodes_related_resources_inode_id_fk
        foreign key (inode_id) references inodes;
CREATE INDEX inode_related_resources_inode_id_idx ON inode_related_resources (inode_id);
-- End Inode Resources Id Collection

-- Inode Labels Many to Many
CREATE TABLE inode_labels(
    inode_id bigint NOT NULL REFERENCES inodes(id),
    label_id bigint NOT NULL REFERENCES label(id)
);
CREATE INDEX inode_labels_inode_id_idx ON inode_labels USING btree (inode_id, label_id);
-- End Inode Labels

-- Inode Security Categories
create table inodes_security_categories (
    inode_id bigint not null,
    security_category int4
);

alter table inodes_security_categories
    add constraint inodes_security_categories_id_fk
        foreign key (inode_id) references inodes;
-- End Inode Security Categories

DROP TABLE file_security_categories;
DROP TABLE file_labels;
DROP TABLE file_node_ids;
DROP TABLE file_metadata;
DROP TABLE file;
DROP TABLE directory;