// SPDX-License-Identifier: Apache-2.0
package ai.intellistream.datahub.models;
import tools.jackson.databind.annotation.JsonSerialize;
import ai.intellistream.datahub.json.ToStringSerializer;

import ai.intellistream.datahub.helpers.datetime.DateTimeHandler;
import com.fasterxml.jackson.annotation.*;
import io.swagger.v3.oas.annotations.media.Schema;
import ai.intellistream.datahub.models.validation.ForbiddenValues;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@EqualsAndHashCode(of = {"id", "externalId"}, callSuper = false)
@Schema(name="Event", description="Event description")
@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_NULL)
@NoArgsConstructor
@JsonPropertyOrder({"id", "externalId", "type", "subType", "*"})
public class EventModel extends AbstractResource{

    /**
     * Unique id reference generated by DataHub.
     */
    //@JsonSerialize(using = ToStringSerializer.class)
    @Schema(description = "The id of the event.", example = "5677892")
    private String id;

    /**
     * The external ID. Unique name for the event, a human read-able ID.
     */
    // @ForbiddenValues matches NodeModel.externalId: an event external id is looked up and hashed
    // the same way a node's is, so the same values have to be off-limits. Events were the one type
    // whose external id skipped this check.
    @NotBlank
    @Size(min = 3, max = 256)
    @ForbiddenValues(message = "Invalid value for external id.")
    @Schema(description = "The external id of the event.", example = "work_order_sap_chemicals", requiredMode = Schema.RequiredMode.REQUIRED)
    private String externalId;

    /**
     * Entity specific metadata. A key-value store.
     */
    @Schema(description = "Event metadata, additional fields you can bind information with.", example = "{\"definition\": \"SAP ORDER PLACED\"}")
    private Map<String, String> metadata = new HashMap<>();

    /**
     * The description of the event.
     */
    @Schema(description = "The description of the event.", example = "This event was caused by....")
    private String description;

    /**
     * The event type.
     */
    // @NotBlank to match the REQUIRED it already advertised: the schema promised a mandatory field
    // while validation would happily accept its absence.
    @NotBlank
    @Size(min = 3, max = 128)
    @Schema(description = "Type of the event", example = "Alarm", requiredMode = Schema.RequiredMode.REQUIRED)
    private String type;

    /**
     * The event subType.
     */
    @Schema(description = "Sub-type of the event", example = "Electrical")
    @Size(min = 3, max = 128)
    private String subType;

    /**
     * The event status.
     */
    @Schema(description = "Status of the event", example = "Status.COMPLETE or FAILED")
    @Size(min = 3, max = 128)
    private String status;

    /**
     * The id of the data set this event belongs to. Optional — events emitted by
     * platform-internal sources (e.g. anomaly detection on a timeseries that is not
     * itself part of a dataset) may have no dataset to attach to.
     */
    @Schema(description = "The id of the data set for this event. Optional.", example = "2323")
    @JsonSerialize(using = ToStringSerializer.class)
    private Long dataSetId;

    /**
     * The resources this event has a relation to. Each entry may be supplied with an id, an
     * externalId, or both; the API resolves the missing side and always returns both. One list
     * rather than two parallel ones is deliberate — parallel id/externalId lists drift.
     */
    @Schema(description = "Resources that this event has a relation to. Supply id, externalId or both; both are returned.",
            example = "[{\"id\": 34, \"externalId\": \"sensor_abc\"}]")
    private List<IdCollection> relatedResources = new ArrayList<>();

    /**
     * The name of the data source containing the primary information about the
     * event.
     */
    @Size(min = 2, max = 128)
    @Schema(description = "The source for this event.", example = "SAP")
    private String source;

    @NotNull
    // The field is a Long (epoch millis) because these DTOs double as Avro payloads and Avro can't
    // handle ZonedDateTime, but the @JsonGetter below serializes it as an ISO-8601 string — so the
    // wire type is "string"/date-time, not a number. On input, either epoch millis or ISO-8601 is
    // accepted (the setter takes a ZonedDateTime). The @Schema must describe the wire type, not the
    // internal Long, or the OpenAPI spec would advertise a numeric epoch the endpoint never emits.
    @Schema(description = "The event time for this event. On output this is an ISO-8601 string; on "
            + "input, either epoch millis [UTC] or ISO-8601 is accepted.",
            type = "string", format = "date-time", example = "2024-08-30T22:00:00Z",
            requiredMode = Schema.RequiredMode.REQUIRED)
    private Long eventTime;

    public String getExternalId(){
        return this.externalId;
    }

    @JsonSetter("eventTime")
    public void setEventTime(ZonedDateTime dateTime) {
        // Null-safe: a missing eventTime stays null so @NotNull validation reports it cleanly,
        // rather than NPEing in DateTimeHandler during request deserialization.
        this.eventTime = dateTime == null ? null : DateTimeHandler.toEpochUTCTime(dateTime);
    }

    public void setEventTime(Long dateTime) {
        this.eventTime = dateTime;
    }

    @JsonGetter("eventTime")
    public ZonedDateTime getEventTime() {
        if(this.eventTime == null) return ZonedDateTime.now(ZoneId.of("UTC"));
        return DateTimeHandler.fromEpochUTCTimeAsZonedDateTime(this.eventTime);
    }

    /**
     * Whether an event time was actually supplied. Unlike {@link #getEventTime()} (which defaults to
     * "now" when unset), this reflects the raw field, so callers can require an explicit event time.
     */
    @JsonIgnore
    public boolean hasEventTime() {
        return this.eventTime != null;
    }

}
