// SPDX-License-Identifier: Apache-2.0
package ai.intellistream.datahub.models;
import tools.jackson.databind.annotation.JsonSerialize;
import ai.intellistream.datahub.json.ToStringSerializer;

import ai.intellistream.datahub.helpers.text.TextValidator;
import ai.intellistream.datahub.models.validation.BoundedMetadata;
import ai.intellistream.datahub.models.validation.FieldLimits;
import ai.intellistream.datahub.validation.resources.RelationshipTypeNotNull;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Size;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

import java.util.HashMap;
import java.util.Map;

@EqualsAndHashCode(of = {"fromExternalId", "toExternalId", "relationshipType", "relationshipTypeId", "fromId", "toId"})
@Schema(name="Relationship", description="Relationship between two resources.")
@Getter
@Setter
@RelationshipTypeNotNull
public class RelForm {

    /**
     * Unique id reference generated by DataHub.
     */
    @JsonSerialize(using = ToStringSerializer.class)
    private Long id;

    private String fromExternalId;

    private String toExternalId;

    @JsonSerialize(using = ToStringSerializer.class)
    private Long fromId;

    @JsonSerialize(using = ToStringSerializer.class)
    private Long toId;

    private String relationshipType;

    @JsonSerialize(using = ToStringSerializer.class)
    private Long relationshipTypeId;

    @BoundedMetadata
    private HashMap<String, String> metadata = new HashMap<>();

    @JsonSerialize(using = ToStringSerializer.class)
    private Long dataSetId;

    @Size(max = FieldLimits.DESCRIPTION_MAX)
    private String description;

    public void setName(String name){
        this.relationshipType = TextValidator.toSnakeUpperCased(name);
    }

    public void setFromExternalId(String s){
        if( s != null ){
            this.fromExternalId = s;
        }
    }

    public void setToExternalId(String s){
        if( s != null ){
            this.toExternalId = s;
        }
    }
}
