// SPDX-License-Identifier: Apache-2.0
package ai.intellistream.datahub.models;

import ai.intellistream.datahub.json.ToStringSerializer;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import tools.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import net.openhft.hashing.LongHashFunction;

import java.util.*;
import java.util.stream.Collectors;

@Schema(name="Resource", description="Resource description")
@Getter
@Setter
@JsonIgnoreProperties(value = { "elementId" })
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({"id", "externalId", "name", "*"})
@ToString(callSuper = true)
public class Resource extends NodeModel {

    /**
     * Unique id reference generated by Neo4j.
     */
    @JsonIgnore
    private String elementId;

    /**
     * resource root, the starting point for navigation resource relations
     */
    @Schema(description = "Is this a root resource?", example = "true")
    private Boolean isRoot = false;

    /**
     * Geographic data. WRITE_ONLY: still accepted as legacy create/update input (assets are
     * created through /resources with an ASSET label), and still a field for the Pulsar Avro
     * payload (the Neo4j consumer reads it off ResourceCudMessage) — but never serialized on
     * REST reads. Typed reads return assets as {@link Asset}, the only DTO whose geoLocation
     * appears on the wire.
     */
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @Valid
    private GeoLocation geoLocation;

    /**
     * If resource is Timeseries, use this field when passing messages. It is not used for the api
     * frontend, so users will not see this.
     */
    @JsonIgnore
    private String valueType = null;

    public Resource() {
    }

}
