// SPDX-License-Identifier: AGPL-3.0-or-later
package ai.intellistream.dhconsole.config;

import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.info.BuildProperties;
import org.springframework.stereotype.Component;

import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;

/**
 * The facts the About dialog shows: which build is running and which backends it talks to.
 *
 * <p>Referenced from {@code layout/main.html} as {@code ${@aboutInfo.version}}. The dialog is the
 * console's AGPL section 13 source offer as well as its version readout, so it is reachable from
 * every page rather than living behind a single controller.
 *
 * <p>{@link BuildProperties} comes from {@code META-INF/build-info.properties}, generated by the
 * {@code bootBuildInfo} task (see build.gradle). It is optional on purpose: a plain
 * {@code java -cp} run or an IDE launch that skips the task must still start, so a missing file
 * degrades to "dev" rather than failing the context. It is resolved per call rather than in the
 * constructor so this bean never depends on being built after the auto-configuration that
 * supplies it.
 */
@Component("aboutInfo")
public class AboutInfo {

    private static final DateTimeFormatter BUILD_TIME =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'").withZone(ZoneOffset.UTC);

    private final ObjectProvider<BuildProperties> buildProperties;
    private final String apiUrl;
    private final String analysisUrl;

    public AboutInfo(ObjectProvider<BuildProperties> buildProperties,
                     @Value("${datahub.url:http://localhost:8081}") String apiUrl,
                     @Value("${datahub.analysis.url:http://localhost:8082}") String analysisUrl) {
        this.buildProperties = buildProperties;
        this.apiUrl = apiUrl;
        this.analysisUrl = analysisUrl;
    }

    public String getVersion() {
        BuildProperties build = buildProperties.getIfAvailable();
        return build != null ? build.getVersion() : "dev";
    }

    /** Formatted build timestamp, or null when this run has no build-info to report. */
    public String getBuildTime() {
        BuildProperties build = buildProperties.getIfAvailable();
        if (build == null || build.getTime() == null) {
            return null;
        }
        return BUILD_TIME.format(build.getTime());
    }

    public String getApiUrl() {
        return apiUrl;
    }

    /** The api's Swagger UI. Assembled here so the template needs no expression arithmetic. */
    public String getSwaggerUrl() {
        return apiUrl + "/swagger-ui.html";
    }

    public String getAnalysisUrl() {
        return analysisUrl;
    }
}
