spring.mvc.static-path-pattern=/static/**

spring.main.lazy-initialization=true
spring.messages.encoding=UTF-8
server.servlet.session.timeout=120m
server.forward-headers-strategy=framework

spring.session.redis.flush-mode=on_save
spring.session.redis.namespace=datahub-console:session
spring.session.timeout=120m
spring.jackson.datetime-feature.write-dates-as-timestamps=false
spring.jackson.datetimefeature.=false
spring.jackson.time-zone=UTC

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false