POST {{hostname}}/timeseries/update
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
	"items": [
		{
			"id": null,
			"externalId": "rust_sdk_test_1400_ts",
			"update": {
				"relationsFrom": {
					"set": null
				}
            }
		}
	]
}

###
POST {{hostname}}/timeseries/update
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "items": [
        {
            "externalId": "test_timeseries_2",
            "update": {
                "name": {
                    "set": "room sensor co2 1001"
                }
            }
        }
    ]
}


###
POST {{hostname}}/timeseries/update
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "items": [
    {
      "id": "236",
      "externalId": null,
      "update": {
        "name": {
          "set": "room sensor co2 1001"
        },
        "externalId": {
          "set": "room_sensor_co2_1001"
        },
        "description": {
          "set": "Air quality sensor"
        },
        "metadata": {
          "set": {
              "measurement_started": "21.11.2023",
              "serial_number": "2930030353"
          }
        },
        "unit": {
          "set": "ppm"
        },
        "dataSetId": {
          "set": 1088
        }
      }
    }
  ]
}

###
POST {{hostname}}/timeseries/update
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "items": [
    {
      "id": null,
      "externalId": "rust_sdk_test_1400_ts",
      "update": {
        "externalId": {
          "set": "rust_sdk_test_1400_ts_renamed",
          "set_null": false
        },
        "name": {
          "set": "Rust SDK Test 1400 TimeSeries Renamed",
          "set_null": false
        },
        "metadata": {
          "set": null,
          "add": {
            "newkey": "newvalue"
          },
          "remove": null
        },
        "unit": {
          "set": "fahrenheit",
          "set_null": false
        },
        "description": {
          "set": "This is test timeseries generated by rust sdk test code. Renamed.",
          "set_null": false
        },
        "unitExternalId": {
          "set": "temperature_deg_f",
          "set_null": false
        },
        "dataSetId": {
          "set": null,
          "set_null": false
        },
        "relationsFrom": {
          "set": null,
          "add": null,
          "remove": null
        },
        "valueType": {
          "set": null,
          "set_null": false
        }
      }
    }
  ]
}
