// SPDX-License-Identifier: Apache-2.0
package ai.intellistream.datahub.label;
import tools.jackson.databind.annotation.JsonSerialize;
import ai.intellistream.datahub.json.ToStringSerializer;

import ai.intellistream.datahub.helpers.text.TextValidator;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

@EqualsAndHashCode(of = {"id", "name"})
@Schema(name="Label", description="Label object")
@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_NULL)
public class LabelForm {

    /**
     * Unique id reference generated by DataHub.
     */
    @Schema(description = "The id of the label object.", example = "5677892")
    @JsonSerialize(using = ToStringSerializer.class)
    private Long id;

    /**
     * The name of the label.
     */
    @Schema(description = "The name of the label object.", example = "NIFI_FUNCTION")
    @NotBlank
    @Size(min = 3, max = 128)
    private String name;

    /**
     * The description of the Label.
     */
    @Schema(description = "The description of the label object.", example = "A function that polls data from a raw source and transform it.")
    private String description;

    /**
     * The language code for the label.
     */
    @Schema(description = "The i18n code of the label object that is used for translation.", example = "nifi.function")
    private String i18nCode;

    /**
     * The color the label will display in the UI.
     */
    @Schema(description = "The color of the label object.", example = "#cc11cc")
    @Size(max = 7)
    private String color;

    public void setName(String name){
        this.name = TextValidator.toSnakeUpperCased(name);
    }
}
